# Generated by Django 4.0.3 on 2023-06-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=20)),
                ('project_title', models.CharField(max_length=20)),
                ('project_image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=20)),
                ('project_title', models.CharField(max_length=20)),
                ('project_image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('write_question', models.CharField(max_length=50)),
            ],
        ),
    ]
