# Generated by Django 4.0.3 on 2023-06-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_detail',
        ),
    ]
